### ISSUE TITLE
[BUG] ValueError with fct_recode() as well as fct_collapse()

### ISSUE THREAD

**Issue by Longistamina** [pwwang/datar#216]
### datar version checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the **latest version** of datar and its backends.

### Issue Description

Hi Mr. Pwwang,

I encoutered another bug while using commands in forcats (fct) to handle factor variables, especially with the numeric factor.

```
import datar.all as dr
from datar import f

# Suppress all warnings
import warnings
warnings.filterwarnings("ignore")

#-------------------------------------#
#-------- Original factor ---------#
#-------------------------------------#

ord_size = dr.ordered(
    x = [39, 42, 36, 40, 38, 41, 39, 37, 42, 40],
    levels = [36, 37, 38, 39, 40, 41, 42]  # specify the order of levels
)

print(ord_size)
# [39, 42, 36, 40, 38, 41, 39, 37, 42, 40]
# Categories (7, int64): [36 < 37 < 38 < 39 < 40 < 41 < 42]

#--------------------------------------#
#-------- dr.fct_collapse() -------#
#--------------------------------------#

collapsed_size = dr.fct_collapse(
    ord_size,
    Small = [36, 37, 38],
    Medium = [39, 40],
    Large = [41, 42]
)

# ValueError: Named values required for recoding factors/categoricals.

# fct_recode() encounters the same problem

'''The code still runs well with string-type factor variable'''

```

### Expected Behavior

```
collapsed_size = dr.fct_collapse(
    ord_size,
    Small = [36, 37, 38],
    Medium = [39, 40],
    Large = [41, 42]
)

print(collapsed_size)
# ['Medium', 'Large', 'Small', 'Medium', 'Small', 'Large', 'Medium', 'Small', 'Large', 'Medium']
# Categories (3, object): ['Small' < 'Medium' < 'Large']
```

### Installed Versions

<details>

>>> datar.get_versions()
python      : 3.12.11 | packaged by conda-forge | (main, Jun  4 2025, 14:45:31) [GCC 13.3.0]
datar       : 0.15.11
simplug     : 0.5.0
executing   : 2.2.0
pipda       : 0.13.1
datar-numpy : 0.3.6
numpy       : 1.26.4
datar-pandas: 0.5.7
pandas      : 2.3.1

</details>

**Comment by pwwang** [comment]
Fixed by [v0.15.12](https://github.com/pwwang/datar/releases/tag/0.15.12).

**Comment by Longistamina** [comment]
Could you please show me how to use it in the right way? It seems that I still encounter the same error (after updating to 0.15.12). Thank you very much Mr. Pwwang, I really appreciate your works.
